language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

cache:
  - pip

# command to install dependencies
before_script:
  - sudo apt-get update
  - sudo apt-get install python3
  - sudo apt-get install python3-pip
  - sudo apt-get install python3-setuptools
  - pip3 install --upgrade setuptools
  - pip3 install -r requirements.txt
  - pip3 install pytest-cov pytest
  - pip3 install codecov
  - pip3 install coveralls
  - pip3 install codacy-coverage
  - sudo apt-get update

# command to run tests
script:
  - pytest -v --cov=./

after_success:
  - codecov
  - coveralls
  - coverage xml
  - export CODACY_PROJECT_TOKEN=d4795dc96ed74f7c8415a2e8c3c42467
  - python-codacy-coverage -r coverage.xml
